### ISSUE TITLE
Installation Troubles

### ISSUE THREAD

**Issue by graphographer** [Polarbitco/gravitate#1]
Running ```gravitate new``` hangs on the Bower installation. But then, as it seems that most of the files are installed, I try to proceed with ```bin/grav install``` and I get "Permission denied". I'm not getting any feedback from Bower, or don't know where to look so I'll let you guide me through this one.

I'm on MacOS Sierra, and I'm using npm 3.5.3 and PHP 7.1 if that helps.

**Comment by graphographer** [comment]
As it turns out, the problem was that I didn't have bower installed. Sorry! Maybe provide an error message for this sort of thing, or put it in the documentation?

**Comment by FalkoJoseph** [comment]
@graphographer hey man, glad you figured it out.
Adding check to see if the dependencies are installed is a good idea.

Thanks for using Gravitate! 👍

**Comment by graphographer** [comment]
I was thinking, wouldn't this be taken care of by including Bower in the
dev dependencies in package.json?
